### ISSUE TITLE
Abandon Forge

### ISSUE THREAD

**Issue by PancakeTAS** [MinecraftTAS/TASmod#101]
Remove all connection to Forge to make it also viable for Fabric

**Comment by PancakeTAS** [comment]
@ScribbleLP 'tis next?

**Comment by ScribbleTAS** [comment]
@MCPfannkuchenYT Forgot to add that to the milestone

**Comment by ScribbleTAS** [comment]
![image](https://github.com/MinecraftTAS/TASmod/assets/28013575/cb7c2d13-147f-4c8f-923b-1ec0dcfecdee)

**Comment by PancakeTAS** [comment]
smh dictionary is wrong
