### ISSUE TITLE
Refactor custom server and package handling

### ISSUE THREAD

**Issue by ScribbleTAS** [MinecraftTAS/TASmod#180]
Rewrite custom server, remove package classes

- [x] Clearinputs
- [x] PlayUntil
- [x] RestartAndPlay
- [x] SaveTAS
- [x] KillTheRNG
- [x] TeleportPacket
- [x] SavestateClientMotion
- [x] SavestatePlayerLoading
- [x] SavestateSave
- [x] SavestateLoad
- [x] TickratechangerSet
- [x] TickratechangerZero
- [x] TickratechangerAdvance

**Comment by PancakeTAS** [comment]
hey hey I'm already done with my part don't u assign this to me (๑>◡<๑)

**Comment by ScribbleTAS** [comment]
@PancakeTAS Let's just say, you were assigned to the wrong issue... ~~Or you didn't do the stuff written in the issue and have done something else entirely~~
