### ISSUE TITLE
Create support for "for loops" in TASfile

### ISSUE THREAD

**Issue by ScribbleTAS** [MinecraftTAS/TASmod#194]

**Comment by PancakeTAS** [comment]
omw to zoom in and out in 2 tick intervals

**Comment by ScribbleTAS** [comment]
The more I think about this, the more it is apparent to me that this is a *bad* idea... You can pretty easily create TASes that never end with a few lines and the technical implementation would be really hacky... You can probably cook something simple up with File Commands, but that won't be me...
