### ISSUE TITLE
F6 Facing HUD label can go above 180.

### ISSUE THREAD

**Issue by nachos1234** [MinecraftTAS/TASmod#217]
If you keeps spinning, the number wont go back down, and it will just keep going up. This is pretty  **annoying** when doing stuff like a true quad45!!!
facing label: ![Image](https://github.com/user-attachments/assets/86cf5ff1-32c4-475c-a756-07d8b644e8a1)

**Comment by ScribbleTAS** [comment]
Yes, this hud has been negleted for a while now and the facing value was more used for testing... Then it was useful to not constrain it...

But this is as simple as using Math.clamp on [this](https://github.com/MinecraftTAS/TASmod/blob/develop/src/main/java/com/minecrafttas/tasmod/gui/InfoHud.java#L288C86-L288C129) value, so not a big change here
