### ISSUE TITLE
Make tickrate 20 during loading to prevent a crash

### ISSUE THREAD

**Issue by ScribbleTAS** [MinecraftTAS/TASmod#37]
Maybe inject into launchIntegratedServer?

**Comment by MGW14** [comment]
Toggle TickSync on, when setGuiScreen(null)

**Comment by PancakeTAS** [comment]
Is this still an issue?

**Comment by ScribbleTAS** [comment]
Problem was serverRunning was never set to false. Launch integrated server had a Thread.sleep() and stop loadWorld has one as well that would softlock mc
