### ISSUE TITLE
Weird delay when after setting current position of the player

### ISSUE THREAD

**Issue by ScribbleTAS** [MinecraftTAS/TASmod#46]

**Comment by ScribbleTAS** [comment]
I will try and do other stuff now and return to this issue... Hopefully this resolves itself

**Comment by ScribbleTAS** [comment]
I DID IT, I FOUND THE ISSUE, YEEEEEEEEEEEESSS  
In the world client the entities only update when they are in the loaded entity list and I needed to delete the client player from the unloadedList to update the player again... Took me 5 days to figure that out, jeez...

**Comment by PancakeTAS** [comment]
#Close
