### ISSUE TITLE
Player is invisible in F5 after savestate

### ISSUE THREAD

**Issue by ScribbleTAS** [MinecraftTAS/TASmod#58]

**Comment by ScribbleTAS** [comment]
Fixes iteself after moving into a new chunk

**Comment by PancakeTAS** [comment]
Player can also place blocks inside of him

**Comment by ScribbleTAS** [comment]
Huh...

**Comment by PancakeTAS** [comment]
Feels like the Player is disconnected from the Chunkmap Clientside

**Comment by ScribbleTAS** [comment]
Just for myself as a reminder: A chunk on the client side has it's own entity list that saves what entity needs to be displayed. And the player is missing in that list. A different problem occurs too, since after a savestate, the chunk you are in is not loaded correctly, so adding the player in manually is not possible since the chunk is just empty... Currently I'm looking into ways of preloading the chunk somehow and adding the player afterwards

**Comment by ScribbleTAS** [comment]
Gave up and let the world tick once after a savestate... can't find a good way of doing it otherwise
