### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by PancakeTAS** [MinecraftTAS/TASmod#63]
I wil create a Documentation, that everyone can read, to try and understand what the heck is happening

**Comment by PancakeTAS** [comment]
It works!

**Comment by ScribbleTAS** [comment]
I can try and host the docs on github pages...

**Comment by PancakeTAS** [comment]
> I wil create a Documentation, that everyone can read, to try and understand what the heck is happening

After some more consideration of this idea i got to the conclusion *jesus fucking christ*
