### ISSUE TITLE
Ticksync does not work as expected

### ISSUE THREAD

**Issue by PancakeTAS** [MinecraftTAS/TASmod#64]
Ticksync does not work how it should... The client should "freeze", and it shouldn't be able to do anything. That also means, that once the Server finishes the Tick, the Client should Tick Once, and Move once. But somewhere in the Code the Client moves X times since the last tick. aka. if the server takes 8 ticks to tick once. The client will move 8 ticks in a single tick.

https://www.youtube.com/watch?v=Vwbhy-cTgZ8

**Comment by ScribbleTAS** [comment]
Reverted to the old system for now...
