### ISSUE TITLE
Player takes longer to break a block after placing a block

### ISSUE THREAD

**Issue by PancakeTAS** [MinecraftTAS/TASmod#88]
Recorded 400 ticks, when playing back it looks away from the Block WAY TO EARLY to break it causing it to desync

**Comment by ScribbleTAS** [comment]
Clue 1:
It may have something to do with high framerates or lagging server

**Comment by ScribbleTAS** [comment]
Clue 2:
https://youtu.be/W2GflxkkzpI

**Comment by ScribbleTAS** [comment]
Clue 3:
Grass takes longer to break than dirt

**Comment by ScribbleTAS** [comment]
Conclusion: It's a vanilla or forge bug
