### ISSUE TITLE
Tickspeed affects gui, chat, and menu

### ISSUE THREAD

**Issue by fartfartfarty** [MinecraftTAS/TASmod#91]
I'd recommend when pressing things like escape and slash that it wont be affected by the tickspeed.

**Comment by PancakeTAS** [comment]
The Tickspeed is used to slow down the game including the gui, which is tick based. We cannot manipulate this vanilla behaviour, because it is an intended Feature. TASmod plays back Minecraft and wrapps around it with the least changed to vanilla Code.
