### ISSUE TITLE
Recording/playback starting from the main menu

### ISSUE THREAD

**Issue by ScribbleTAS** [MinecraftTAS/TASmod#99]
Currently, you need to enter a world to start a playback/recording. Recording outside the minecraft world on a closed integrated server already works, but the current system is a bit tedious.  

## Goals:
* Be able to start a recording from the main menu and go into a world instead of having to start already in the world
* Start a playback when launching the game

## To Do
- [x] #112
- [x] #120
- [x] Let the command quit the player to the main menu
- [x] Mix into the GuiMainMenu constructor to launch a recording
- [x] Make a savestate when you are executing `/fullrecord` and call it savestate 0
  
- [x] Create a new `/play` command `/fullplay`
- [x] Let the command quit the player to the main menu
- [x] Load savestate 0
  
- [x] Fix #37

**Comment by PancakeTAS** [comment]
Hey, I'm from the TAS Discord, I wanted to help program! wait what
